# -*- coding: utf-8 -*-
from config import database, helpers, db_context
helpers.extent_model(
            "LMSLS_ExExamination",
            "base",
            [["exam_id"]],
            exam_id=helpers.create_field("text", True),
            exam_name1=helpers.create_field("text", True),
            exam_name2=helpers.create_field("text"),
            course_related=float,
            course_info=helpers.create_field("object"),
            exam_avail=helpers.create_field("bool"),
            specific_avail=helpers.create_field("object"),
            exam_mode=float,
            exam_form=float,
            who_take_exam =helpers.create_field("list"),
            assign_candidate = helpers.create_field("text"),
            choose_from=helpers.create_field("bool"),
            mode_pick = helpers.create_field("text"),
            question_category = helpers.create_field("list"),
            exam_category = helpers.create_field("text"),
            exam_temp_name1= helpers.create_field("text"),
            question_list=helpers.create_field("list",False,dict(
                ques_category=helpers.create_field("text"),
            )),
            retake_time_list=helpers.create_field("list"),
            retake_exam = helpers.create_field("object"),
            retake_all = helpers.create_field("text"),
            retake_condition = helpers.create_field("text"),
            result_less = helpers.create_field("text"),
            retake_time = float,
            different_time = helpers.create_field("bool"),
            list_time_retake=helpers.create_field("list"),
            range_time =helpers.create_field("object"),
            scoring_method= helpers.create_field("text"),
            show_result= helpers.create_field("text"),
            customize= helpers.create_field("text"),
            minium_score= helpers.create_field("text"),
            add_feedback= helpers.create_field("text"),
            result_type= helpers.create_field("text"),
            assign_exam= helpers.create_field("text"),
            minimum_score= float,
            certificate= helpers.create_field("bool"),
            display_result= helpers.create_field("text"),
            ques_order= helpers.create_field("text"),
            ques_navi = helpers.create_field("bool"),
            allow_candidates = helpers.create_field("bool"),
            preview_time= helpers.create_field("bool"),
            text_high  = helpers.create_field("bool"),
            ques_dis = float,
            result_SMS = helpers.create_field("bool"),
            result_email = helpers.create_field("bool"),
            pause_resume = helpers.create_field("bool"),
            check_plagi = helpers.create_field("bool"),
            show_hint = helpers.create_field("bool"),
            duration=helpers.create_field("text"),
            edit_instruction=helpers.create_field("text"),
            status = helpers.create_field("bool"),
            disable = helpers.create_field("bool"),
            note = helpers.create_field("text"),
            certificate_template = helpers.create_field("text"),

        )
def LMSLS_ExExamination():
    ret = db_context.collection("LMSLS_ExExamination")

    return ret